name: Auto Update Collection and Pull Request

on:
  issue_comment:
    types: [created]

jobs:
  update-markdown-and-create-pr:
    if: github.event.comment.body == 'looks good to me' && github.event.issue.assignee.login == github.event.comment.user.login
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch Issue Details
      id: issue
      uses: octokit/request-action
      with:
        route: GET /repos/${{ github.repository }}/issues/${{ github.event.issue.number }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Update Markdown File
      run: |
        ISSUE_TITLE=$(echo "${{ steps.issue.outputs.data }}" | jq -r '.title')
        ISSUE_BODY=$(echo "${{ steps.issue.outputs.data }}" | jq -r '.body')
        echo "## Issue: $ISSUE_TITLE" >> articles/about/collection.md
        echo "$ISSUE_BODY" >> articles/about/collection.md
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add path/to/your/file.md
        git commit -m 'Automated update to markdown file with issue details'

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'Automated update to markdown file with issue details'
        branch: 'auto-update-md-branch'
        title: 'Automated Update to Collection File'
