name: Add Issue to Collection

on:
  issue_comment:
    types: [created]

jobs:
  add-to-collection:
    if: ${{ github.event.comment.body == 'looks good to me' }}
    runs-on: ubuntu-latest
    permissions:
      issues: read
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Get Issue Content
        id: issue
        uses: actions/github-script@v7
        with:
          script: |
            const issueNumber = context.payload.issue.number;
            const issueData = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.name,
              issue_number: issueNumber
            });
            console.log('Issue data:', issueData.data);
            return issueData.data.body || '';
          result-encoding: string

      - name: Update Collection File
        id: update-file
        run: |
          mkdir -p articles/about
          if [ ! -f articles/about/collection.md ]; then
            touch articles/about/collection.md
          fi
          # Ensure there's a newline at the end of the file if it's not empty
          if [ -s articles/about/collection.md ] && [ $(tail -c1 articles/about/collection.md | wc -l) -eq 0 ]; then
            echo "" >> articles/about/collection.md
          fi
          # Add the new content
          echo "- ${ISSUE_BODY}" >> articles/about/collection.md
        env:
          ISSUE_BODY: ${{ steps.issue.outputs.result }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: 'docs: add issue #${{ github.event.issue.number }} to collection'
          title: 'Add Issue #${{ github.event.issue.number }} to Collection'
          body: |
            This PR adds the content from issue #${{ github.event.issue.number }} to the collection.
            
            Original issue: ${{ github.event.issue.html_url }}
          branch: add-issue-${{ github.event.issue.number }}
          base: main
          delete-branch: true
